[package]
name = "tangothreadmeasurements"
version = "1.0.0"
edition = "2024"

[dev-dependencies]
tango-bench = "0.6.0"
# tango-bench = { version = "1.0.0", path="../tango/tango-bench" }

[[bench]]
name = "bencha"
harness = false
